# Generated by Django 6.0.2 on 2026-02-17 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twotails", "0002_alter_address_options_alter_cart_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiration_days",
            field=models.PositiveIntegerField(default=30, verbose_name="Срок годности"),
        ),
        migrations.AddField(
            model_name="product",
            name="manufactured_by",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата изготовления"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создан"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создан"
            ),
        ),
    ]
