# Generated by Django 6.0.2 on 2026-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twotails", "0003_product_expiration_days_product_manufactured_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
    ]
