# Generated by Django 6.0.2 on 2026-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twotails", "0004_alter_cartitem_quantity_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(verbose_name="Цена продажи"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_percent",
            field=models.PositiveIntegerField(verbose_name="Процент скидки"),
        ),
    ]
