# Generated by Django 6.0.2 on 2026-02-16 18:27

import django.db.models.deletion
import twotails.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twotails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Элемент корзины",
                "verbose_name_plural": "Элементы корзины",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name": "Доставка", "verbose_name_plural": "Доставки"},
        ),
        migrations.AlterModelOptions(
            name="deliveryitem",
            options={
                "verbose_name": "Элемент доставки",
                "verbose_name_plural": "Элементы доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Элемент заказа",
                "verbose_name_plural": "Элементы заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="productpromotion",
            options={
                "verbose_name": "Товар-акция",
                "verbose_name_plural": "Товары-акции",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Акция", "verbose_name_plural": "Акции"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Роль", "verbose_name_plural": "Роли"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "permissions": [
                    ("confirm_supply", "Может подтверждать поставку"),
                    ("cancel_supply", "Может отменять поставку"),
                    ("change_order_item_status", "Может менять статус поставки"),
                    ("can_edit_delivery_items", "Может редактировать состав поставки"),
                    ("view_own_deliveries", "Может просматривать свои поставки"),
                    ("view_own_products", "Может просматривать свои товары"),
                    ("view_own_orders", "Может просматривать заказы с его товарами"),
                    (
                        "view_own_sales_report",
                        "Может просматривать отчёты по своим продажам",
                    ),
                ],
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="current_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Текущее количество"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0, verbose_name="Процент скидки"),
        ),
        migrations.AddField(
            model_name="product",
            name="has_discount",
            field=models.BooleanField(default=False, verbose_name="Скидка"),
        ),
        migrations.AddField(
            model_name="product",
            name="last_delivery_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество в последней поставке"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line",
            field=models.CharField(max_length=120, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=20, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основной адрес"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активная"),
                    ("converted", "Конвертированная"),
                    ("abandoned", "Брошенная"),
                ],
                max_length=9,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="twotails.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="twotails.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=25, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="twotails.category",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата доставки"),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("confirmed", "Подтверждена"),
                    ("rejected", "Отклонена"),
                    ("assembling", "Сборка"),
                    ("in_progress", "В пути"),
                    ("received", "Исполнена"),
                    ("canceled", "Отменена"),
                ],
                default="pending",
                max_length=11,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twotails.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="twotails.delivery",
                verbose_name="Доставка",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twotails.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("paid", "Оплачен"),
                    ("shipped", "Отправлен"),
                    ("cancelled", "Отменён"),
                ],
                max_length=9,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(verbose_name="Общая сумма"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twotails.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_at_purchase",
            field=models.FloatField(verbose_name="Цена на момент покупки"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twotails.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twotails.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(max_length=100, verbose_name="Производитель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Название товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(
                through="twotails.ProductPromotion",
                to="twotails.promotion",
                verbose_name="Акции",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.IntegerField(verbose_name="Закупочная цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.IntegerField(verbose_name="Цена продажи"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twotails.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="productpromotion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="twotails.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="twotails.promotion",
                verbose_name="Акция",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_percent",
            field=models.IntegerField(verbose_name="Процент скидки"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="is_active",
            field=models.BooleanField(verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название акции"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Название роли"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Название поставщика"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=twotails.models.User.get_default_role,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="twotails.role",
                verbose_name="Роль",
            ),
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата поставки"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to="twotails.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка",
                "verbose_name_plural": "Поставки",
            },
        ),
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="twotails.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="twotails.supply",
                        verbose_name="Поставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент поставки",
                "verbose_name_plural": "Элементы поставки",
            },
        ),
    ]
